[[markets]]
slug    = "will-gavin-newsom-win-the-2028-democratic-presidential-nomination-568"
profile = "live-tiny"
enabled = true

[[markets]]
slug    = "will-jd-vance-win-the-2028-republican-presidential-nomination"
profile = "live-tiny"
enabled = true
